<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php $options = $block->decorateArray($block->getOptions()); ?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>,
                "controlContainer": ".field.option"
            }
        }
    }
</script>
        <fieldset class="fieldset fieldset-bundle-options">
            <?php echo $block->getChildHtml('product_info_bundle_options_top');?>
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?php echo $block->getOptionHtml($option) ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?php /* @escapeNotVerified */ echo __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>


<script type="text/javascript">
  
  require(['jquery','Magento_Ui/js/modal/modal'],function($, modal){


        $(document).on('click', '.opemmodalpopup',  function(){

            var options = {
                type: 'popup',
                title: $(this).attr('data-pro-name'),
                responsive: true,
                innerScroll: true,
                footer: false,
            };

            var modalForm = $(this).attr('data-form');
            var popup = modal(options, $(modalForm));
            $(modalForm).modal("openModal");
        });

        $(document).on('click', '.addItem',  function(){
            var modalForm1 = $(this).attr('data-bundle-option');
            $('#'+modalForm1).trigger('click');
            this.closeModal();
        });

        var acc = document.getElementsByClassName("label");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].onclick = function(){
                this.classList.toggle("active","slow");
                var control = this.nextElementSibling;
                if (control.style.display === "block") {
                    control.style.display = "none";
                } else {
                    control.style.display = "block";
                }
            }
        }

  });

</script>