<?php

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $_product = $block->getProduct();
    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>

<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
<div id="bundleSummary"
     class="block-bundle-summary"
     data-mage-init='{"sticky":{"container": ".product-add-form"}}'>
    <div class="content">
        <div class="bundle-summary">
            <strong class="subtitle"><?php /* @escapeNotVerified */ echo __('Summary'); ?></strong>
            <div id="bundle-summary" data-container="product-summary">
                <ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
                <script data-template="bundle-summary" type="text/x-magento-template">
                    <li>
                        <strong class="label 123"><%- data._label_ %>:</strong>
                        <div data-container="options"></div>
                    </li>
                </script>
                <script data-template="bundle-option" type="text/x-magento-template">
                    <div class="smry-option"><?php /* @escapeNotVerified */ echo __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?>
                        <div class="price-option"><?php echo  __('%1', '<%- data._price_ %>'); ?></div>
                        <div class="close-link"><a class="close remove-product-from-cart" data-id="bundle_option[<%- data._id_ %>][<%- data._option_ %>]" href="javascript:void(0)"></a></div>
                    </div>


                </script>
            </div>
        </div>
        <?php echo $block->getChildHtml('', true);?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()): ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>

<?php endif; ?>

<script type="text/javascript">
require(['jquery','Xumulus_AdvanceBundles/js/jquery.sticky'],function($,sticky){
    
    $(document).ready(function(){
        $("#bundleSummary").sticky({topSpacing:0});


    });

    // $(window).scroll(function(){

    //     var elementPos = $('#bundleSummary').offset().top;
    //     var documentHeight = $(document).height();
    //     var distanceFromBottom = documentHeight - elementPos;

    //     if(distanceFromBottom < 700){
            
    //         $("#bundleSummary").unstick({topSpacing:0});       
    //     }

    // });

  $(document).on('click', '.remove-product-from-cart',  function(){
            var modalData = $(this).attr('data-id');
            $("input[name='"+modalData+"']").click();
        });
});
</script>

