<?php

    $_product = $block->getProduct();
?>

<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
<div class="field option kit-smry">
        <h3 class="label bundle-toggle">
            <span><?php /* @escapeNotVerified */ echo __($_product->getName().' Summary'); ?></span>
        </h3>
        <div class="control" id="bundle-summary" data-container="product-summary">
            <div class="nested options-list btm-smry">
                <ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
                <script data-template="bundle-summary" type="text/x-magento-template">
                    <li class="accodion-items">
                        <strong class="label 123"><%- data._label_ %>:</strong>
                        <div data-container="options"></div>
                    </li>
                </script>
                <script data-template="bundle-option" type="text/x-magento-template">
                    <div class="smry-option" ><?php /* @escapeNotVerified */ echo __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?>
                         <div class="price-option"><?php echo  __('%1', '<%- data._price_ %>'); ?></div>
                         <div class="close-link"><a class="close remove-product-from-cart" data-id="bundle_option[<%- data._id_ %>][<%- data._option_ %>]" href="javascript:void(0)"></a></div>
                    </div>
                </script>
            <?php echo $block->getChildHtml('', true);?>
            </div>
        </div>
</div>
<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()): ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>
<script type="text/javascript">
     require(['jquery'],function($){

        var acc = document.getElementsByClassName("label");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].onclick = function(){
                this.classList.toggle("active","slow");
                var control = this.nextElementSibling;
                if (control.style.display === "block") {
                    control.style.display = "none";
                } else {
                    control.style.display = "block";
                }
            }
        }

       /* $(document).on('click', '.remove-product-from-cart',  function(){
            var modalData = $(this).attr('data-id');
            alert(modalData);
            $("input[name='"+modalData+"']").click();
        });*/

  });
</script>
<?php endif; ?>