<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox $block */ ?>
<?php $_option = $block->getOption();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <h3 class="label bundle-toggle">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </h3>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
        <div class="accodion-items">	            
                <a class="action opemmodalpopup" href="#" data-pro-name="<?php echo $_selections[0]->getName();?>" data-form="#modal-form-<?php echo $_selections[0]->getSelectionId();?>">
                  <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                </a>
                <?php $image_url = $imageHelper->init($_selections[0], 'product_page_image_small')->setImageFile($_selections[0]->getFile())->resize(50,50)->getUrl();
                $image_url_medium = $imageHelper->init($_selections[0], 'product_page_image_small')->setImageFile($_selections[0]->getFile())->resize(300,300)->getUrl();
                ?>
                <input type="hidden"
                       class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                       value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>

                <div class="modal-form" id="modal-form-<?php echo $_selections[0]->getSelectionId();?>" style="display: none;">
                  <?php
                      $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_selections[0]->getId());
                  ?>
                    <div class="productImage"><img src="<?php echo $image_url_medium ;?>" /></div>
                    <div class="productDesc"><?php echo $product->getDescription();?></div>
                </div>
                <div class="image-thumb">
    	             <img alt="<?php echo $image_url_medium ;?>" src="<?php echo $image_url ;?>" />
	                 <div class="large"></div>
                 </div>
             </div>
            <?php else:?>
                <?php foreach($_selections as $_selection): ?>
                	<div class="accodion-items">
                        <?php $image_url = $imageHelper->init($_selection, 'product_page_image_small')->setImageFile($_selection->getFile())->resize(50,50)->getUrl();
                        $image_url_medium = $imageHelper->init($_selection, 'product_page_image_small')->setImageFile($_selection->getFile())->resize(300,300)->getUrl();
                        ?>                    
                    <div class="image-thumb">
    	                <img alt="<?php echo $image_url_medium ;?>" src="<?php echo $image_url ;?>" />
	                    <div class="large"></div>
                    </div>                    
                    <div class="field choice">
                        <input class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> checkbox product bundle option change-container-classname"
                               id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                               type="checkbox"
                               <?php if ($_option->getRequired()) /* @escapeNotVerified */ echo 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' . $_option->getId() . ']&quot;]:checked\'}"'?>
                               name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                               data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                               <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                               <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                               value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"/>
                        <label class="label"
                               for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>">
                            <a class="action opemmodalpopup" href="#" data-pro-name="<?php echo $_selection->getName();?>" data-form="#modal-form-<?php echo $_selection->getSelectionId();?>" data-check="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"><span><?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selection) ?></span></a>
                        </label>

                    </div>
                     <div class="modal-form" id="modal-form-<?php echo $_selection->getSelectionId();?>" style="display: none;">
                      <?php
                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_selection->getId());
                    ?>
                        <div class="productImage"><img src="<?php echo $image_url_medium ;?>" /></div>
                        <div class="productDesc"><?php echo $product->getDescription();?></div>
                        <div class="addbutton"><input type="button" class="addItem" data-bundle-option="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>" name="addItem" value="Add this Item" data-role="action" /></div>
                        <div class="itemAdded"><?php echo __('This item is added');?></div>
                    </div>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>